version: '3'

services:
  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: latex_microservice
    container_name: app
    volumes:
      - ./app:/app
    ports:
      - "8888:80"
    env_file:
      - .env
    # command: uvicorn main:app --reload --host 0.0.0.0 --port 8888
