### Multipart form with only tex (unicode)
POST {{host}}/api/pdf
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="tex"
Content-Type: text/plain

Some Information that should be a latex file </> \\ 👍🏼  " '
--boundary

> {%
client.test("success", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Multipart form with multiple media files.
POST {{host}}/api/pdf
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="tex"
Content-Type: text/plain

Some Information that should be a latex file </> \\ 👍🏼  " '
--boundary
Content-Disposition: form-data; name="media"; filename="some.pdf"
Content-Type: application/pdf

< ../assets/lorum_ipsum.pdf
--boundary
Content-Disposition: form-data; name="media"; filename="another.pdf"
Content-Type: application/pdf

< ../assets/lorum_ipsum.pdf
--boundary

> {%
client.test("success", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### JSON test (will fail) 422
POST {{host}}/api/pdf
Content-Type: application/json

{"tex": "goo bar"}

> {%
client.test("success", function() {
  client.assert(response.status === 422, "Response status is not 422");
});
%}


### Actual PDF call
POST {{host}}/api/pdf
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="tex"
Content-Type: text/plain

< ../assets/test.tex
--boundary
